server:
  port: ${BOOKING_SERVICE_PORT:8084}

spring:
  application:
    name: payment-service

  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/driverapp_payment_db}
    representation:
      uuid: standard

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081}